### PR TITLE
Fixes for using endorsement hierarchy

### PR DESCRIPTION
**Pull request by dgarske**
* Fixes for attestation with endorsement key. 
* Enable the broken endorsement tests.
* Fix native test `TPM2_PolicyPCR`.
* Remove the `WOLFTPM2_KEYBLOB.name` (deprecated) and is in `handle.name` now.
* Improve `TPM2_GetRCString` error rendering to correctly resolve RC_WARN. Add parameter, session and handle debug information. Refactor line length / alignment. Remove duplicate "success".
* Fix CMake build broken since cryptocb refactor in PR #304.
* Added CI tests for CMake.

Fixes https://github.com/wolfSSL/wolfTPM/issues/282

### CODE REVIEW

**Comment by embhorn** [comment]
cmake build error:

```
[ 21%] Linking C executable bin/activate_credential
/usr/bin/ld: libwolftpm.so: undefined reference to `wolfTPM2_CryptoDevCb'
/usr/bin/ld: libwolftpm.so: undefined reference to `wolfTPM2_ClearCryptoDevCb'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/activate_credential.dir/build.make:99: bin/activate_credential] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:192: CMakeFiles/activate_credential.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

File: examples/run_examples.sh
Comment (embhorn) [inline examples/run_examples.sh:1]: Spelling line 42:
`echo -e "Ken Generation Tests"`
...should be "Key"

File: src/tpm2.c [hunk 1]
```diff
@@ -5540,7 +5540,7 @@ const char* TPM2_GetRCString(int rc)
     /* for negative return codes use wolfCrypt */
     if (rc < 0) {
         switch (rc) {
-            TPM_RC_STR(TPM_RC_TIMEOUT, "Hardware timeout");
+            TPM_RC_STR(TPM_RC_TIMEOUT,           "Hardware timeout");
```
Comment (embhorn) [inline src/tpm2.c:5543]: Whitespace

**Review by embhorn — CHANGES_REQUESTED** [review]
Tested with RPi / Infineon TPM

Fix spelling issue and review cmake error

**Review by embhorn — APPROVED** [review]
Excellent
